version: '3.3'

services:
    mongo:
        image: mongo:4.2.6-bionic
        restart: "no"
        volumes:
            - ./mongo-data/:/data/db/:rw
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=nl7QkdoQiqIEnSse8IMgBUfEp7gOThr2
        command: --quiet
    crawler:
        build: ./crawler
        restart: "no"
        volumes:
            - ./crawler/src/:/leetnews/crawler/src/:ro
    api:
        build: ./api
        restart: "no"
        volumes:
            - ./api/src/:/leetnews/api/src/:ro
        ports:
            - 127.0.0.1:41080:80
