name: leetnews_crawler
description: fills up mongo with posts
homepage: https://leetnews.net

environment:
    sdk: '>=2.5.0 <3.0.0'

dependencies:
    uuid: ^2.0.4
    mongo_dart: ^0.4.0
    xml: ^4.1.0
    html: ^0.14.0+3
    html_unescape: ^1.0.1+3
